[packages.fedora]
copr.install = [
    "atim/starship",
    "dejan/lazygit",
    "jdxcode/mise"
]

copr.remove = [
    "atim/lazygit"
]

dnf = [
    "zsh",
    "starship",
    "lazygit",
    "git-delta",
    "bat",
    "zoxide",
    "xl2tpd",
    "NetworkManager-l2tp",
    "NetworkManager-l2tp-gnome",
    "mise"
]
